# Generated by Django 3.2.4 on 2021-07-09 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_elevation_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentinel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to='uploads/Raster/%Y/%m/%d')),
                ('color_ramps', models.CharField(blank=True, choices=[('viridis', 'viridis'), ('plasma', 'plasma'), ('inferno', 'inferno'), ('magma', 'magma'), ('cividis', 'cividis'), ('Greys', 'Greys'), ('Purples', 'Purples'), ('Blues', 'Blues'), ('Greens', 'Greens'), ('Oranges', 'Oranges'), ('Reds', 'Reds'), ('YlOrBr', 'YlOrBr'), ('YlOrRd', 'YlOrRd'), ('OrRd', 'OrRd'), ('PuRd', 'PuRd'), ('RdPu', 'RdPu'), ('BuPu', 'BuPu'), ('GnBu', 'GnBu'), ('PuBu', 'PuBu'), ('YlGnBu', 'YlGnBu'), ('PuBuGn', 'PuBuGn'), ('BuGn', 'BuGn'), ('YlGn', 'YlGn'), ('PiYG', 'PiYG'), ('PRGn', 'PRGn'), ('BrBG', 'BrBG'), ('PuOr', 'PuOr'), ('RdGy', 'RdGy'), ('RdBu', 'RdBu'), ('RdYlBu', 'RdYlBu'), ('RdYlGn', 'RdYlGn'), ('Spectral', 'Spectral'), ('coolwarm', 'coolwarm'), ('bwr', 'bwr'), ('seismic', 'seismic')], max_length=100)),
                ('uploaded_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
    ]
