# Generated by Django 3.2.5 on 2021-07-20 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20210720_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeoutputspng',
            name='sentinel_id',
        ),
        migrations.AddField(
            model_name='changeoutputspng',
            name='sentinel_1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_1', to='world.sentinel'),
        ),
        migrations.AddField(
            model_name='changeoutputspng',
            name='sentinel_2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_2', to='world.sentinel'),
        ),
        migrations.CreateModel(
            name='ClusteringOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='outputs/cluster_output/%Y/%m/%d')),
                ('uploaded_date', models.DateField(blank=True, default=datetime.date.today)),
                ('sentinel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.sentinel')),
            ],
        ),
    ]
