# Generated by Django 3.2.5 on 2021-07-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20210720_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sentinel',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.groups'),
        ),
    ]
