# Generated by Django 3.2.5 on 2021-07-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_auto_20210720_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elevation',
        ),
        migrations.AddField(
            model_name='changeoutputspng',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.groups'),
        ),
        migrations.AlterField(
            model_name='changeoutputspng',
            name='file',
            field=models.FileField(upload_to='outputs/change_outputs/%Y/%m/%d'),
        ),
    ]
