# Generated by Django 3.2.5 on 2021-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_auto_20210721_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentinel',
            name='color_ramps',
            field=models.CharField(choices=[('viridis', 'viridis'), ('plasma', 'plasma'), ('inferno', 'inferno'), ('magma', 'magma'), ('cividis', 'cividis'), ('Greys', 'Greys'), ('Purples', 'Purples'), ('Blues', 'Blues'), ('Greens', 'Greens'), ('Oranges', 'Oranges'), ('Reds', 'Reds'), ('YlOrBr', 'YlOrBr'), ('YlOrRd', 'YlOrRd'), ('OrRd', 'OrRd'), ('PuRd', 'PuRd'), ('RdPu', 'RdPu'), ('BuPu', 'BuPu'), ('GnBu', 'GnBu'), ('PuBu', 'PuBu'), ('YlGnBu', 'YlGnBu'), ('PuBuGn', 'PuBuGn'), ('BuGn', 'BuGn'), ('YlGn', 'YlGn'), ('PiYG', 'PiYG'), ('PRGn', 'PRGn'), ('BrBG', 'BrBG'), ('PuOr', 'PuOr'), ('RdGy', 'RdGy'), ('RdBu', 'RdBu'), ('RdYlBu', 'RdYlBu'), ('RdYlGn', 'RdYlGn'), ('Spectral', 'Spectral'), ('coolwarm', 'coolwarm'), ('bwr', 'bwr'), ('seismic', 'seismic')], max_length=100, null=True),
        ),
    ]
