# Generated by Django 3.2.5 on 2021-07-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_alter_sentinel_color_ramps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangeOutputsPNG',
            new_name='ChangeOutputs',
        ),
    ]
